### ISSUE TITLE
Difference between “unit list” vs “conic” obs?

### ISSUE THREAD

**Issue by Chulabhaya** [FLAIROx/JaxMARL#100]
Hey there! I’m really interested in using SMAX for a project and as such have been trying to go through the code and understand better how everything works. As part of that I wanted to ask, how does the “unit list” obs work vs the “conic” obs (is it just that the former has a circular FoV around the agent while the latter has a cone view in front of the agent)? And which is the best representation that most closely matches SMAC v2? I may have missed it but I didn't find references about these two different types of obs in any of the documentation for SMAX (neither in paper nor blog post). Thank you!

**Comment by amacrutherford** [comment]
Hey! Conic obs is something we are playing around with internally, use "unit list" as this is what is close to smacv2
