### ISSUE TITLE
Question regarding Overcooked V2 observations

### ISSUE THREAD

**Issue by ConstantinRuhdorfer** [FLAIROx/JaxMARL#102]
Hi,

Thanks again for working on JaxMARL. It has been lovely building on top of it so far!
One quick question, I recently noticed the following comment in the Overcooked observation function 

https://github.com/FLAIROx/JaxMARL/blob/fdf659579ae2feceed1a859173500de98ccd64d7/jaxmarl/environments/overcooked/overcooked.py#L238

I am interested in a Overcooked that has much denser observations and was wondering whether someone has put some thought into how such item-embedding based observations would look like?

Cheers, Constantin

**Comment by lupuandr** [comment]
Hi Constantin,

We have thought briefly about how to improve observations. One approach is learned embeddings. Another is to hardcode an encoding of each cell, akin to how [Minigrid does it.](https://github.com/Farama-Foundation/Minigrid/blob/016fb0db11d693840a2d379ecd609452eb670ae4/minigrid/core/world_object.py#L66). In this case, you'd have to carefully account for overlapping items and variable item states (e.g. pot cooking)

We are currently working on an Overcooked V2 (where improved observations is one part of it), and will open-source it when ready, likely in a few months.

**Comment by ConstantinRuhdorfer** [comment]
Hi,

Thanks for getting back so quickly! I see, to me this looks quite similar to the `maze_map` in Overcooked, i.e. [here](https://github.com/FLAIROx/JaxMARL/blob/fdf659579ae2feceed1a859173500de98ccd64d7/jaxmarl/environments/overcooked/overcooked.py#L192C1-L207C10) where we encode each grid cell. Am I getting this correctly? 

Awesome that you are working on Overcooked V2, I guess at this point you are not willing to share details on how your new observations will look like? I am personally interested in cross-level generalization in Overcooked and this is why I am looking into making observations less sparse so it is quite interesting to me. I am looking forward to see what you will come up with!
