### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'define_bool_state'

### ISSUE THREAD

**Issue by paulzyzy** [FLAIROx/JaxMARL#108]
Hi, when I try to run mappo_rnn_mpe.py, this error shows: 
return jax_config.define_bool_state('flax_' + name, default, help)
AttributeError: 'Config' object has no attribute 'define_bool_state'
So I googled a bit and tried to upgrade or downgrade the version of followings:
jax>=0.4.16.0,<=0.4.25
jaxlib>=0.4.16.0,<=0.4.25
flax==0.7.4
But there would be another errors show up including:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxmarl 0.0.5 requires jax<=0.4.25,>=0.4.16.0, but you have jax 0.4.31 which is incompatible.
jaxmarl 0.0.5 requires jaxlib<=0.4.25,>=0.4.16.0, but you have jaxlib 0.4.31 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
orbax-checkpoint 0.5.17 requires jax>=0.4.25, but you have jax 0.4.24 which is incompatible.

I am wondering if you could take a look at this and share some tips with me. Thanks!

**Comment by amacrutherford** [comment]
Hey! have you tried using our Dockerfile?

**Comment by dav3-b** [comment]
@amacrutherford Nope, but thanks for pointing it out, I'll definitely try it!
