### ISSUE TITLE
Question about refactoring baselines/IPPO/ippo_ff_overcooked.py

### ISSUE THREAD

**Issue by LukavdBoogaard** [FLAIROx/JaxMARL#109]
Hi! 

I am using this repository for my master's thesis. I attempted to refactor baselines/IPPO/ippo_ff_overcooked.py by moving out methods to the global scope (instead of defining them in the make_train method). 

My attempts have proven difficult. When moving a method to the global scope, the variables (which used to be in its scope by default) now have to be passed as arguments. This creates problems for classes that I want to pass into the method such as the ActortCritic class, which gives  the following error:
```python
TypeError: Value ActorCritic(
    # attributes
    action_dim = 6
    activation = 'tanh'
) with type <class '__main__.ActorCritic'> is not a valid JAX type
```

I guess my question is: did you guys write this file like this because you had to or do you think a refactored version with all (or most) methods at the global scope is possible?

**Comment by amacrutherford** [comment]
Hey! Glad it's proving useful for your thesis. We wrote the baseline as single file implementations for clarity (inspired by CleanRL). However, doing it a different way is definitely possible. Have a look at [XLand](https://github.com/corl-team/xland-minigrid/blob/main/training/train_single_task.py) as their code is more modular
