### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by shray** [FLAIROx/JaxMARL#111]
I have been struggling to figure out how to save checkpoints, for example, in "ippo_ff_overcooked.py". Can you point me to how I could do it here?

**Comment by amacrutherford** [comment]
Hey! of course, an example is [here](https://github.com/FLAIROx/JaxMARL/blob/29fbca77cdf3a0e1205d86dacedf5666d17e5239/baselines/MAPPO/mappo_rnn_hanabi.py#L564) in `mappo_rnn_hanabi.py`:
