### ISSUE TITLE
Jax versioning

### ISSUE THREAD

**Issue by sash-a** [FLAIROx/JaxMARL#116]
Hey guys :wave: 

Just wondering if there's any reason you pin Jax to `0.4.25`? We are having issues on Mava using JaxMARL as it uses a newer version of Jax and soon will be incompatible with `0.4.25`. I don't think it would cause any issues if you unpin, but I haven't done a thorough check.

The culprit PR on mava: https://github.com/instadeepai/Mava/pull/1103

**Comment by wangreit** [comment]
Hi!

I am getting the following errors when running the colab walkthrough.  I think it's also related to the incompatible issues with Jax, Jaxlib, and flax.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 0.34.2 requires safetensors>=0.4.3, but you have safetensors 0.4.2 which is incompatible.
dopamine-rl 4.0.9 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.

Could you please take a look?  

Thanks!

**Comment by amacrutherford** [comment]
Hey! @sash-a hope all is well!! Yea this is a very fair catch, we'll take a look at it. There are a few API changes that we haven't actioned but should

**Comment by sash-a** [comment]
Thanks Alex all is going great hope you're doing well also. Happy to help with a PR if you need :smile:

**Comment by amacrutherford** [comment]
@sash-a yes please go ahead and start it if you guys have time, we're all running around a bit at the moment :)

**Comment by amacrutherford** [comment]
no worries!! it was actually simpler than thought so should be fixed with #123

**Comment by sash-a** [comment]
Thanks for the fix!
