### ISSUE TITLE
one error in mappo_rnn_smax.py

### ISSUE THREAD

**Issue by shengchao-y** [FLAIROx/JaxMARL#117]
There seems to be an error in the initialization of critic_train_state.
Should the apply_fn be critic_network? No idea whether this may lead to any issues.

https://github.com/FLAIROx/JaxMARL/blob/42e7d638aa5dab88757c95c22f0486af8ec85694/baselines/MAPPO/mappo_rnn_smax.py#L258
`
critic_train_state = TrainState.create( 
            apply_fn=actor_network.apply, 
            params=critic_network_params, 
            tx=critic_tx, 
        )
`

**Comment by amacrutherford** [comment]
Yep that is wrong, thanks for catching!
