### ISSUE TITLE
Usage of Flashbax

### ISSUE THREAD

**Issue by EdanToledo** [FLAIROx/JaxMARL#46]
Hello everyone, 

Amazing work you've done here! I see you've updated your algorithms to use Flashbax. Glad you thought it was a worthwhile change to make. I thought I'd just give my two cents as to how its being used in the q learning scripts. Looking at your use case it would make more sense to use the trajectory buffer instead of the flat buffer. Usually one would add trajectories sequentially and allow these trajectories to be sampled in a variety of ways (any possible subsequence). If I understand correctly, what you are doing here is adding entire trajectories as data items that are then being sampled in a batch. Either option is valid and have their benefits but in both cases a trajectory buffer would be more apt. In your exact use case, a trajectory buffer with entire trajectories being stored as data items would simply use a sample_sequence_length=1 and any desired batch size. This would be faster as you're performing less indexing in the sampling function and I found that there are pretty significant indexing issues with JAX right now on certain accelerators.

This might not be worth your time to change as the performance gains would be only slight but I thought I'd let you know.

**Comment by amacrutherford** [comment]
@mttga !

**Comment by mttga** [comment]
Hi Edan,

thank you very much for reaching out! We really appreciate your contribution in refining our use of flashbax. Regarding the replacement of the current flat buffer with a trajectory buffer, I concur with your suggestion. Currently, our implementation is as follows:

```
# INIT
buffer = fbx.make_flat_buffer(
    max_length=config['BUFFER_SIZE'],
    min_length=config['BUFFER_BATCH_SIZE'],
    sample_batch_size=config['BUFFER_BATCH_SIZE'],
    add_sequences=True,
    add_batch_size=None,
)
# sample_traj_unbatched is (max_time_steps, ...)
buffer_state = buffer.init(sample_traj_unbatched)

# ADDING
# sample_traj is (max_time_steps, num_envs)
buffer_traj_batch = jax.tree_util.tree_map(lambda x:jnp.swapaxes(x, 0, 1), sample_traj) # put the batch size (num envs) in first axis
buffer_state = buffer.add(buffer_state, buffer_traj_batch)

# SAMPLING
rng, _rng = jax.random.split(rng)
learn_traj = buffer.sample(buffer_state, _rng).experience.first # (batch_size, max_time_steps, ...)
learn_traj = jax.tree_map(lambda x: jnp.swapaxes(x, 0, 1), learn_traj) # (max_time_steps, batch_size, ...)
```

Do you agree that the following would be more appropriate?

```
# INIT
# Instantiate the trajectory buffer, which is a NamedTuple of pure functions.
buffer = fbx.make_trajectory_buffer(
    max_length_time_axis=config['BUFFER_SIZE']//config['NUM_ENVS'],
    min_length_time_axis=config['BUFFER_BATCH_SIZE'],
    sample_batch_size=config['BUFFER_BATCH_SIZE'],
    add_batch_size=config['NUM_ENVS'],
    sample_sequence_length=1,
    period=1,
)
# sample_traj_unbatched is (max_time_steps, ...)
buffer_state = buffer.init(sample_traj_unbatched) 

# ADDING
# sample_traj is (max_time_steps, num_envs)
buffer_traj_batch = jax.tree_util.tree_map(
    lambda x:jnp.swapaxes(x, 0, 1)[:, np.newaxis], # put the batch dim first and add a dummy sequence dim
    sample_traj
) # (num_envs, 1, time_steps, ...)
buffer_state = buffer.add(buffer_state, buffer_traj_batch)

# SAMPLING
rng, _rng = jax.random.split(rng)
learn_traj = buffer.sample(buffer_state, _rng).experience # (batch_size, 1, max_time_steps, ...)
learn_traj = jax.tree_map(
    lambda x: jnp.swapaxes(x[:, 0], 0, 1), # remove the dummy sequence dim (1) and swap batch and temporal dims
    learn_traj
) # (max_time_steps, batch_size, ...)
```

Additionally, I'd like to mention that my approach was inspired by the _DQN with Vectorised Gym Environments_ notebook featured on the [examples page](https://instadeepai.github.io/flashbax/#examples) of Flashbax.
