### ISSUE TITLE
Confusion around RNN hidden size in baseline implementation

### ISSUE THREAD

**Issue by ConstantinRuhdorfer** [FLAIROx/JaxMARL#51]
Hi 👋 ,

Lovely repo! I was playing around with your implementation and specifically have a question regarding your RNN implementations.
I am unfamiliar with the Jax details but I keep wondering about these lines:

```python
init_hstate = jnp.reshape(
    init_hstate, (config["NUM_STEPS"], config["NUM_ACTORS"])
)
```

For example here: https://github.com/FLAIROx/JaxMARL/blob/cd5f0565eb703ee27d9987d4af4f7671aa5a123b/baselines/IPPO/ippo_rnn_mpe.py#L318C24-L318C24

Shouldn't the dimension of the hstate be independent of the number of steps? Specifically, as I understand your implementation I would expect the initial hidden state to have dimension `(size_embedding, num_actors)` (transposed) and as its the initial hidden state of the RNN? Consequently, only changing the number of steps make the scripts I tested crash. What am I missing here?

Thanks!

**Comment by amacrutherford** [comment]
Hey! You're not missing anything, they should be independent. It is on our to-do list to make this change. (for an independent implementation look at [minimax](https://github.com/facebookresearch/minimax/blob/2ae9e04d37f97d7c14308f5a26237dcfca63470f/src/minimax/models/common.py#L142))
