### ISSUE TITLE
Add Multi-Agent Swimmer from MaMuJoCo

### ISSUE THREAD

**Issue by MathisFederico** [FLAIROx/JaxMARL#53]
I would like to use [multi-agent Swimmer](https://robotics.farama.org/envs/MaMuJoCo/ma_swimmer/) as a test-bed for trivial multi-agent cooperation, but sadly it is not available in the list of mabrax environments yet.

As the mappings are quite simple, maybe partitioning "2x1" and "3x1" could be added ?

Thanks !

**Comment by luchris429** [comment]
@gardarjuto are there any plans for this on your end?

**Comment by gardarjuto** [comment]
Hey and sorry for the late response!

It is true, the mappings are quite simple and it should be fairly easy to add them similar to how the other mappings are done.
Tbh I didn't plan to add it but it's part of the same family and is already implemented in brax so would make sense. If you've got it working already @MathisFederico, please send a PR and we'll add it in!
