### ISSUE TITLE
Error when running colab example in quickstart

### ISSUE THREAD

**Issue by keep9oing** [FLAIROx/JaxMARL#55]
I'm just running example code of colab in the readme file (quick start).
But the error comes out as below. (Part1 in the notebook)
![bug](https://github.com/FLAIROx/JaxMARL/assets/31655488/51b439f4-d58f-42a6-a10f-f32bb00f93d3)

What I did is just run cells sequentially.
I'm using colab pro+ with T4 GPU.

Thank you

**Comment by alexunderch** [comment]
Hey! This error is related to `numpy` version used in Colab and its compatibility with the library.
Usually, if you restart the runtime after the installation, it should resolve your issue.

**Comment by keep9oing** [comment]
Thanks, restart the session solved this problem.

**Comment by alexunderch** [comment]
Can you please close the issue if there are no more problems?
