### ISSUE TITLE
How to integrate marl-eval in JaxMARL

### ISSUE THREAD

**Issue by fmxFranky** [FLAIROx/JaxMARL#59]
Hi!
Amazing work you've done here! I wanna integrate `marl-eval` in JaxMARL, can you give me some snippets about it?
Thank you very much!

**Comment by amacrutherford** [comment]
Hey! So as far as I am aware `marl-eval` needs the experimental results data to be in a particular form which could be achieved by amending our logging code to fit their requirements. It is on our list to do but is not a priority for now. Let me know if this helps!

**Comment by RuanJohn** [comment]
Hey there @fmxFranky, we just made a new release `MARL-eval` release today that now adds a logger that will handle most of the heavy lifting for you in terms of logging in our required format. Please have a look at the logger and some other new JSON tools we have added to repo [here](https://github.com/instadeepai/marl-eval/blob/main/docs/json_tooling_usage.md). For an example of how we set up the `MARL-eval` JSON logger in `Mava` please also see [here](https://github.com/instadeepai/Mava/blob/60dabf3b3c47489f365de66fc64c21e866b56d43/mava/utils/logger.py#L224).
