### ISSUE TITLE
Is gridworld included in the library?

### ISSUE THREAD

**Issue by GPaolo** [FLAIROx/JaxMARL#62]
First of all, thanks for the amazing work!

I have seen that gridworld is included in the library, but it's in a separate folder. Is it usable as it is or it's not yet officially an usable environment?

**Comment by amacrutherford** [comment]
Hey! It's not an official environment but was used during the development of some of the grid-based environments, that said the dependency no longer exists. If you're looking at a maze-solving problem then please do submit a PR and we can add it as a proper environment!

**Comment by GPaolo** [comment]
Ok will do once I have set it up! Thanks!
