### ISSUE TITLE
Add example of animation with MAPPO trained agent

### ISSUE THREAD

**Issue by satpreetsingh** [FLAIROx/JaxMARL#64]
Would it be possible to add a simple example animation of a MAPPO trained agent? 

I don't see it here:
https://colab.research.google.com/github/FLAIROx/JaxMARL/blob/main/jaxmarl/tutorials/JaxMARL_Walkthrough.ipynb

Nor do I see it in any of the baselines etc.

Ideally, the agent will be saved to disk and reloaded for generating the animation. Thank you!

**Comment by amacrutherford** [comment]
Hey! Providing weights for pre-trained agents is on our TODO list but not a priority. You can generate a gif of the MAPPO agent using the training script provided in the baselines folder

**Comment by satpreetsingh** [comment]
Sorry I meant to ask for a simple example of _inference_ using a MAPPO trained agent. The animation/save/reload were frills that were easy to figure out from your existing code. 

I'd like to see your recommended (or canonical) way to reuse the agent/network classes outside the training loop. Thanks!
