### ISSUE TITLE
Suggestion of integrating HARL algorithms

### ISSUE THREAD

**Issue by fmxFranky** [FLAIROx/JaxMARL#65]
Hello. Thank you for your amazing work. I appreciate the efforts to provide a unified library of MARL algorithms and environments for benchmarking and reproducibility. To better achieve this goal, I suggest integrating HARL algorithms, which achieve SOTA results on various benchmarks and are theoretically underpinned. Their papers have been accepted to JMLR and ICLR 2024 (spotlight). As they represent important advancements in MARL and are now increasingly used as baselines, integrating them should be helpful to the adoption of this library.

**Comment by amacrutherford** [comment]
Hey! If you'd like to submit these as PR's that would be fantastic
