### ISSUE TITLE
Why are HIDDEN_SIZE and NUM_STEPS tied to 128?

### ISSUE THREAD

**Issue by satpreetsingh** [FLAIROx/JaxMARL#68]
Hi, why are the RNN HIDDEN_SIZE and NUM_STEPS tied to 128? Other values seem to throw tensor reshaping errors. 

Tried on IPPO and MAPPO with MPE, e.g. with NUM_STEPS=256: 
```
TypeError: cannot reshape array of shape (256, 100) (size 25600) into shape (128, 100) (size 12800)
```

I don't immediately see a reason from the algorithm why these should be tied up.

**Comment by amacrutherford** [comment]
Hey! This was a simplification we made when collecting baselines, it is fixed in [this file](https://github.com/FLAIROx/JaxMARL/blob/main/baselines/IPPO/ippo_rnn_smax.py) by adding `config["GRU_HIDDEN_DIM"]`. We are looking to update the rest of the scripts over the next month.
