### ISSUE TITLE
Feature request: Support POLA

### ISSUE THREAD

**Issue by cool-RR** [FLAIROx/JaxMARL#84]
I would like to run experiments using opponent shaping, possibly the POLA algorithm. I previously looked at Pax and the M-FOS algorithm, but I would like to avoid the meta-game mechanics if possible. 

I'm guessing that POLA couldn't be implemented in JaxMARL in a straightforward way because agents need to be aware of each other's gradients, which is different than most RL algorithms.

I'm considering working on this implementation and any changes to JaxMARL needed to support POLA. **I would appreciate if you could tell me whether you think that's possible, what the difficulties would be, whether this is something you'll be interested in merging, and any other insights about this potential project.**

**Comment by alexunderch** [comment]
Can you give some reference link to get known with the algorithm?

**Comment by cool-RR** [comment]
Sure: 

* [POLA paper](https://arxiv.org/abs/2210.10125)
* [POLA reference implementation](https://github.com/Silent-Zebra/POLA/)

**Comment by cool-RR** [comment]
Thanks @alexunderch ! Besides the implementation, it's also important for me to hear from the maintainers whether it aligns with their vision for the package, because I don't want to be maintaining a fork. Tag me when you push this branch.

**Comment by luchris429** [comment]
You're right that we don't plan on doing this right now! I think it would be harder in this repo than in pax. I'd recommend trying to fork that repo instead if you can! [pax](https://github.com/ucl-dark/pax/tree/main/pax/agents/lola).
